language: node_js
node_js:
  - "stable"
stages:
  - lint
  - name: docs
    if: branch = main
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: docs
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        github_url: github.com
        keep_history: false
        local_dir: dist
        on:
          branch: main
